---
- name: Get all generated config files
  find:
    paths: '{{ encryption_location }}'
    recurse: yes
  register: config_files

- name: Fetch files from remote
  fetch:
    src: '{{ item.path }}'
    dest: '../.generated/{{ item.path }}'
    flat: yes
  with_items: '{{ config_files.files }}'
  loop_control:
    label: "{{ item.path }}"