---
- set_fact:
    query_expression: "[?host=='{{ inventory_hostname }}'].ip"
- set_fact:
    etcd_internal_ip: '{{ kubernetes_master_nodes | json_query(query_expression) | first }}'
      
- name: Create etcd service config
  template:
    src: 'etcd.service'
    dest: '/etc/systemd/system/etcd.service'

- name: Start and enable etcd service
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: started
