---
- name: Download control plane binaries - crictl
  get_url:
    url: '{{ item }}'
    dest: '{{ kubernetes_setup_location }}/'
  with_items: 
    - '{{ worker_binaries_sources.crio }}'

- name: Extract crictl
  unarchive:
    src: '{{ kubernetes_setup_location }}/crictl-v{{ worker_binaries_versions.crio }}-linux-amd64.tar.gz'
    dest: '/usr/local/bin'
    mode: 0755
    remote_src: yes

- name: Link crictl to usr bin
  file:
    src: /usr/local/bin/crictl
    dest: /usr/bin/crictl
    state: link
