---
- name: Create the containerd configuration file
  template:
    src: containerd/config.toml
    dest: /etc/containerd/config.toml

- name: Create the containerd.service systemd unit file
  template:
    src: containerd/containerd.service
    dest: /etc/systemd/system/containerd.service
  
- name: Start and enable containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started
