---
- name: Verifies if swap is enabled
  raw: swapon --show
  changed_when: false
  register: swap_info

- name: Disables swap if enabled
  raw: |
    sed -i '/swap/d' /etc/fstab
    sudo swapoff -a
  when: swap_info.stdout != ""