---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ certificates_client_server_kubernetes_api_server_location }}'

- name: Create kubernetes api server json configuration files for cfssl
  template:
    src: 'kubernetes-csr.json'
    dest: '{{ certificates_client_server_kubernetes_api_server_location }}/kubernetes-csr.json'
  register: server_cert_info

- set_fact:
    kubernetes_master_hosts: "{{ item.host }}"
    kubernetes_master_ips: "{{ item.ip }}"
  with_items: '{{ kubernetes_master_nodes }}'
  when: server_cert_info is changed

- name: Generate kubernetes api server certificates
  shell: |
    cfssl gencert \
      -ca={{ certificates_ca_location }}/ca.pem \
      -ca-key={{ certificates_ca_location }}/ca-key.pem \
      -config={{ certificates_ca_location }}/ca-config.json \
      -profile=kubernetes \
      -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,{{ kubernetes_master_ips }},127.0.0.1,{{ kubernetes_master_hosts }} \
      kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: '{{ certificates_client_server_kubernetes_api_server_location }}'
  when: server_cert_info is changed