---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ certificates_service_account_key_pair_location }}'

- name: Create service account key pair json configuration files for cfssl
  template:
    src: 'service-account-csr.json'
    dest: '{{ certificates_service_account_key_pair_location }}/service-account-csr.json'
  register: ca_cert_info

- name: Generate service account key pair certificates
  shell: |
    cfssl gencert \
      -ca={{ certificates_ca_location }}/ca.pem \
      -ca-key={{ certificates_ca_location }}/ca-key.pem \
      -config={{ certificates_ca_location }}/ca-config.json \
      -profile=kubernetes \
      service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: '{{ certificates_service_account_key_pair_location }}'
  when: ca_cert_info is changed