---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '/opt/kubernetes/config'
    - '/opt/kubernetes/config/cert'
    - '/opt/kubernetes/config/cert/ca'

- name: Create ca json configuration files for cfssl
  template:
    src: '{{ item }}'
    dest: '/opt/kubernetes/config/cert/ca/{{ item }}'
  with_items:
    - ca-config.json
    - ca-csr.json
  register: ca_cert_info

- name: Generate ca certificates
  shell: 'cfssl gencert -initca ca-csr.json | cfssljson -bare ca'
  args:
    chdir: '/opt/kubernetes/config/cert/ca'
  when: ca_cert_info is changed