---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ kubernetes_config_location }}'
    - '{{ certificates_location }}'

- import_tasks: cert.ca.yml
  when: inventory_hostname in groups['setup_node']

- import_tasks: cert.client_server.yml
  when: inventory_hostname in groups['setup_node']

- import_tasks: cert.service_account_key_pair.yml
  when: inventory_hostname in groups['setup_node']

- import_tasks: distribute.yml