---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ kubernetes_config_location }}'
    - '{{ certificates_location }}'

- import_tasks: cert.ca.yml
- import_tasks: cert.client_server.yml
- import_tasks: cert.service_account_key_pair.yml