kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "{{ kubernetes_proxy_lib_location }}/kubeconfig"
mode: "iptables"
clusterCIDR: "10.200.0.0/16"