---
- name: Download control plane binaries
  get_url:
    url: '{{ kubernetes_control_plane_base_url }}/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0555
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Link control plane binaries to usr bin
  file:
    src: '/usr/local/bin/{{ item }}'
    dest: '/usr/bin/{{ item }}'
    state: link
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler