---
kubernetes_config_location: '/opt/kubernetes/config'
kubernetes_setup_location: '/opt/kubernetes/setup'

certificates_location: '{{ kubernetes_config_location }}/cert'

certificates_ca_location: '{{ certificates_location }}/ca'
certificates_ca: '{{ certificates_ca_location }}/ca.pem'

certificates_client_server_location: '{{ certificates_location }}/client_server'
certificates_client_server_kubernetes_api_server_location: '{{ certificates_client_server_location }}/kubernetes_api_server'
certificates_client_server_kubernetes_api_server: '{{ certificates_client_server_kubernetes_api_server_location }}/kubernetes.pem'
certificates_client_server_kubernetes_api_server_key: '{{ certificates_client_server_kubernetes_api_server_location }}/kubernetes-key.pem'

etcd_version: 'v3.4.0'
etcd_url: 'https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz'
etcd_location: '/etc/etcd'
etcd_lib_location: '/var/lib/etcd'