---
- name: '[{{ task_label }}] Create {{ kubeconfig_file }}'
  shell: |
    kubectl config set-cluster '{{ kubernetes_cluster_name }}' \
      --certificate-authority='{{ certificates_ca_location }}/ca.pem' \
      --embed-certs=true \
      --server=https://{{ kubernetes_controller_ips }}:6443 \
      --kubeconfig='{{ kubeconfig_file }}'

    kubectl config set-credentials '{{ credential_name }}' \
      --client-certificate='{{ client_certificate }}' \
      --client-key='{{ client_key }}' \
      --embed-certs=true \
      --kubeconfig='{{ kubeconfig_file }}'
    
    kubectl config set-context default \
      --cluster='{{ kubernetes_cluster_name }}' \
      --user='{{ credential_name }}' \
      --kubeconfig='{{ kubeconfig_file }}'

    kubectl config use-context default \
      --kubeconfig='{{ kubeconfig_file }}'
  args:
    chdir: '{{ kubeconfig_location }}'
    creates: '{{ kubeconfig_file }}'